export const GoogleTranslateLanguages: Record<string, string> = {
  Automatic: 'auto',
  Afrikaans: 'af',
  Albanian: 'sq',
  Amharic: 'am',
  Arabic: 'ar',
  Armenian: 'hy',
  Azerbaijani: 'az',
  Basque: 'eu',
  Belarusian: 'be',
  Bengali: 'bn',
  Bosnian: 'bs',
  Bulgarian: 'bg',
  Catalan: 'ca',
  Cebuano: 'ceb',
  Chichewa: 'ny',
  Chinese_Simplified: 'zh-CN',
  Chinese_Traditional: 'zh-TW',
  Corsican: 'co',
  Croatian: 'hr',
  Czech: 'cs',
  Danish: 'da',
  Dutch: 'nl',
  English: 'en',
  Esperanto: 'eo',
  Estonian: 'et',
  Filipino: 'tl',
  Finnish: 'fi',
  French: 'fr',
  Frisian: 'fy',
  Galician: 'gl',
  Georgian: 'ka',
  German: 'de',
  Greek: 'el',
  Gujarati: 'gu',
  Haitian_Creole: 'ht',
  Hausa: 'ha',
  Hawaiian: 'haw',
  Hebrew: 'iw',
  Hindi: 'hi',
  Hmong: 'hmn',
  Hungarian: 'hu',
  Icelandic: 'is',
  Igbo: 'ig',
  Indonesian: 'id',
  Irish: 'ga',
  Italian: 'it',
  Japanese: 'ja',
  Javanese: 'jw',
  Kannada: 'kn',
  Kazakh: 'kk',
  Khmer: 'km',
  Korean: 'ko',
  Kurdish_Kurmanji: 'ku',
  Kyrgyz: 'ky',
  Lao: 'lo',
  Latin: 'la',
  Latvian: 'lv',
  Lithuanian: 'lt',
  Luxembourgish: 'lb',
  Macedonian: 'mk',
  Malagasy: 'mg',
  Malay: 'ms',
  Malayalam: 'ml',
  Maltese: 'mt',
  Maori: 'mi',
  Marathi: 'mr',
  Mongolian: 'mn',
  Myanmar_Burmese: 'my',
  Nepali: 'ne',
  Norwegian: 'no',
  Pashto: 'ps',
  Persian: 'fa',
  Polish: 'pl',
  Portuguese: 'pt',
  Punjabi: 'pa',
  Romanian: 'ro',
  Russian: 'ru',
  Samoan: 'sm',
  Scots_Gaelic: 'gd',
  Serbian: 'sr',
  Sesotho: 'st',
  Shona: 'sn',
  Sindhi: 'sd',
  Sinhala: 'si',
  Slovak: 'sk',
  Slovenian: 'sl',
  Somali: 'so',
  Spanish: 'es',
  Sundanese: 'su',
  Swahili: 'sw',
  Swedish: 'sv',
  Tajik: 'tg',
  Tamil: 'ta',
  Telugu: 'te',
  Thai: 'th',
  Turkish: 'tr',
  Ukrainian: 'uk',
  Urdu: 'ur',
  Uzbek: 'uz',
  Vietnamese: 'vi',
  Welsh: 'cy',
  Xhosa: 'xh',
  Yiddish: 'yi',
  Yoruba: 'yo',
  Zulu: 'zu',
};

export const GoogleTranslate2Languages: Record<string, string> = {
  Automatic: 'auto',
  Afrikaans: 'af',
  Albanian: 'sq',
  Amharic: 'am',
  Arabic: 'ar',
  Armenian: 'hy',
  Azerbaijani: 'az',
  Basque: 'eu',
  Belarusian: 'be',
  Bengali: 'bn',
  Bosnian: 'bs',
  Bulgarian: 'bg',
  Catalan: 'ca',
  Cebuano: 'ceb',
  Chichewa: 'ny',
  Chinese_Simplified: 'zh-CN',
  Chinese_Traditional: 'zh-TW',
  Corsican: 'co',
  Croatian: 'hr',
  Czech: 'cs',
  Danish: 'da',
  Dutch: 'nl',
  English: 'en',
  Esperanto: 'eo',
  Estonian: 'et',
  Filipino: 'tl',
  Finnish: 'fi',
  French: 'fr',
  Frisian: 'fy',
  Galician: 'gl',
  Georgian: 'ka',
  German: 'de',
  Greek: 'el',
  Gujarati: 'gu',
  Haitian_Creole: 'ht',
  Hausa: 'ha',
  Hawaiian: 'haw',
  Hebrew: 'iw',
  Hindi: 'hi',
  Hmong: 'hmn',
  Hungarian: 'hu',
  Icelandic: 'is',
  Igbo: 'ig',
  Indonesian: 'id',
  Irish: 'ga',
  Italian: 'it',
  Japanese: 'ja',
  Javanese: 'jw',
  Kannada: 'kn',
  Kazakh: 'kk',
  Khmer: 'km',
  Korean: 'ko',
  Kurdish_Kurmanji: 'ku',
  Kyrgyz: 'ky',
  Lao: 'lo',
  Latin: 'la',
  Latvian: 'lv',
  Lithuanian: 'lt',
  Luxembourgish: 'lb',
  Macedonian: 'mk',
  Malagasy: 'mg',
  Malay: 'ms',
  Malayalam: 'ml',
  Maltese: 'mt',
  Maori: 'mi',
  Marathi: 'mr',
  Mongolian: 'mn',
  Myanmar_Burmese: 'my',
  Nepali: 'ne',
  Norwegian: 'no',
  Pashto: 'ps',
  Persian: 'fa',
  Polish: 'pl',
  Portuguese: 'pt',
  Punjabi: 'pa',
  Romanian: 'ro',
  Russian: 'ru',
  Samoan: 'sm',
  Scots_Gaelic: 'gd',
  Serbian: 'sr',
  Sesotho: 'st',
  Shona: 'sn',
  Sindhi: 'sd',
  Sinhala: 'si',
  Slovak: 'sk',
  Slovenian: 'sl',
  Somali: 'so',
  Spanish: 'es',
  Sundanese: 'su',
  Swahili: 'sw',
  Swedish: 'sv',
  Tajik: 'tg',
  Tamil: 'ta',
  Telugu: 'te',
  Thai: 'th',
  Turkish: 'tr',
  Ukrainian: 'uk',
  Urdu: 'ur',
  Uzbek: 'uz',
  Vietnamese: 'vi',
  Welsh: 'cy',
  Xhosa: 'xh',
  Yiddish: 'yi',
  Yoruba: 'yo',
  Zulu: 'zu',
};

export const LibreTranslateLanguages: Record<string, string> = {
  Automatic: 'auto',
  English: 'en',
  Arabic: 'ar',
  Azerbaijani: 'az',
  Chinese_Simplified: 'zh',
  Czech: 'cs',
  Danish: 'da',
  Dutch: 'nl',
  Esperanto: 'eo',
  Finnish: 'fi',
  French: 'fr',
  German: 'de',
  Greek: 'el',
  Hebrew: 'iw',
  Hindi: 'hi',
  Hungarian: 'hu',
  Indonesian: 'id',
  Irish: 'ga',
  Italian: 'it',
  Japanese: 'ja',
  Korean: 'ko',
  Persian: 'fa',
  Polish: 'pl',
  Portuguese: 'pt',
  Russian: 'ru',
  Slovak: 'sk',
  Spanish: 'es',
  Swedish: 'sv',
  Turkish: 'tr',
  Ukrainian: 'uk',
};

export const ArgosTranslateLanguages: Record<string, string> = {
  Automatic: 'auto',
  English: 'en',
  Arabic: 'ar',
  Chinese_Simplified: 'zh',
  French: 'fr',
  German: 'de',
  Hindi: 'hi',
  Indonesian: 'id',
  Irish: 'ga',
  Italian: 'it',
  Japanese: 'ja',
  Korean: 'ko',
  Polish: 'pl',
  Portuguese: 'pt',
  Russian: 'ru',
  Spanish: 'es',
  Turkish: 'tr',
  Vietnamese: 'vi',
};

export const BingTranslateLanguages: Record<string, string> = {
  Automatic: 'auto-detect',
  Afrikaans: 'af',
  Albanian: 'sq',
  Amharic: 'am',
  Arabic: 'ar',
  Armenian: 'hy',
  Assamese: 'as',
  Azerbaijani: 'az',
  Bangla: 'bn',
  Bashkir: 'ba',
  Basque: 'eu',
  Bosnian: 'bs',
  Bulgarian: 'bg',
  Cantonese_Traditional: 'yue',
  Catalan: 'ca',
  Chinese_Literary: 'lzh',
  Chinese_Simplified: 'zh-Hans',
  Chinese_Traditional: 'zh-Hant',
  Croatian: 'hr',
  Czech: 'cs',
  Danish: 'da',
  Dari: 'prs',
  Divehi: 'dv',
  Dutch: 'nl',
  English: 'en',
  Estonian: 'et',
  Faroese: 'fo',
  Fijian: 'fj',
  Filipino: 'fil',
  Finnish: 'fi',
  French: 'fr',
  French_Canada: 'fr-CA',
  Galician: 'gl',
  Georgian: 'ka',
  German: 'de',
  Greek: 'el',
  Gujarati: 'gu',
  Haitian_Creole: 'ht',
  Hebrew: 'he',
  Hindi: 'hi',
  Hmong: 'mww',
  Hungarian: 'hu',
  Icelandic: 'is',
  Indonesian: 'id',
  Inuinnaqtun: 'ikt',
  Inuktitut: 'iu',
  Inuktitut_Latin: 'iu-Latn',
  Irish: 'ga',
  Italian: 'it',
  Japanese: 'ja',
  Kannada: 'kn',
  Kazakh: 'kk',
  Khmer: 'km',
  Klingon_Latin: 'tlh-Latn',
  Korean: 'ko',
  Kurdish_Kurmanji: 'ku',
  Kurdish_Northern: 'kmr',
  Kyrgyz: 'ky',
  Lao: 'lo',
  Latvian: 'lv',
  Lithuanian: 'lt',
  Macedonian: 'mk',
  Malagasy: 'mg',
  Malay: 'ms',
  Malayalam: 'ml',
  Maltese: 'mt',
  Marathi: 'mr',
  Mongolian_Cyrillic: 'mn-Cyrl',
  Mongolian: 'mn-Mong',
  Myanmar_Burmese: 'my',
  Māori: 'mi',
  Nepali: 'ne',
  Norwegian: 'nb',
  Odia: 'or',
  Pashto: 'ps',
  Persian: 'fa',
  Polish: 'pl',
  Portuguese_Brazil: 'pt',
  Portuguese: 'pt-PT',
  Punjabi: 'pa',
  Querétaro_Otomi: 'otq',
  Romanian: 'ro',
  Russian: 'ru',
  Samoan: 'sm',
  Serbian_Cyrillic: 'sr-Cyrl',
  Serbian: 'sr-Latn',
  Slovak: 'sk',
  Slovenian: 'sl',
  Somali: 'so',
  Spanish: 'es',
  Swahili: 'sw',
  Swedish: 'sv',
  Tahitian: 'ty',
  Tamil: 'ta',
  Tatar: 'tt',
  Telugu: 'te',
  Thai: 'th',
  Tibetan: 'bo',
  Tigrinya: 'ti',
  Tongan: 'to',
  Turkish: 'tr',
  Turkmen: 'tk',
  Ukrainian: 'uk',
  Upper_Sorbian: 'hsb',
  Urdu: 'ur',
  Uyghur: 'ug',
  Uzbek: 'uz',
  Vietnamese: 'vi',
  Welsh: 'cy',
  Yucatec_Maya: 'yua',
  Zulu: 'zu',
};

export const DeepLTranslateLanguages: Record<string, string> = {
  Bulgarian: 'BG',
  Chinese_Simplified: 'ZH',
  Czech: 'CS',
  Danish: 'DA',
  Dutch: 'NL',
  English: 'EN',
  Estonian: 'ET',
  Finnish: 'FI',
  French: 'FR',
  German: 'DE',
  Greek: 'EL',
  Hungarian: 'HU',
  Indonesian: 'ID',
  Italian: 'IT',
  Japanese: 'JA',
  Korean: 'KO',
  Latvian: 'LV',
  Lithuanian: 'LT',
  Norwegian: 'NB',
  Polish: 'PL',
  Portuguese: 'PT',
  Romanian: 'RO',
  Russian: 'RU',
  Slovak: 'SK',
  Slovenian: 'SL',
  Spanish: 'ES',
  Swedish: 'SV',
  Turkish: 'TR',
  Ukrainian: 'UK',
};

export const GTPTranslateLanguages: Record<string, string> = {
  Automatic: 'auto',
  Afrikaans: 'af',
  Albanian: 'sq',
  Amharic: 'am',
  Arabic: 'ar',
  Armenian: 'hy',
  Azerbaijani: 'az',
  Basque: 'eu',
  Belarusian: 'be',
  Bengali: 'bn',
  Bosnian: 'bs',
  Bulgarian: 'bg',
  Catalan: 'ca',
  Cebuano: 'ceb',
  Chichewa: 'ny',
  Chinese_Simplified: 'zh-CN',
  Chinese_Traditional: 'zh-TW',
  Corsican: 'co',
  Croatian: 'hr',
  Czech: 'cs',
  Danish: 'da',
  Dutch: 'nl',
  English: 'en',
  Esperanto: 'eo',
  Estonian: 'et',
  Filipino: 'tl',
  Finnish: 'fi',
  French: 'fr',
  Frisian: 'fy',
  Galician: 'gl',
  Georgian: 'ka',
  German: 'de',
  Greek: 'el',
  Gujarati: 'gu',
  Haitian_Creole: 'ht',
  Hausa: 'ha',
  Hawaiian: 'haw',
  Hebrew: 'iw',
  Hindi: 'hi',
  Hmong: 'hmn',
  Hungarian: 'hu',
  Icelandic: 'is',
  Igbo: 'ig',
  Indonesian: 'id',
  Irish: 'ga',
  Italian: 'it',
  Japanese: 'ja',
  Javanese: 'jw',
  Kannada: 'kn',
  Kazakh: 'kk',
  Khmer: 'km',
  Korean: 'ko',
  Kurdish_Kurmanji: 'ku',
  Kyrgyz: 'ky',
  Lao: 'lo',
  Latin: 'la',
  Latvian: 'lv',
  Lithuanian: 'lt',
  Luxembourgish: 'lb',
  Macedonian: 'mk',
  Malagasy: 'mg',
  Malay: 'ms',
  Malayalam: 'ml',
  Maltese: 'mt',
  Maori: 'mi',
  Marathi: 'mr',
  Mongolian: 'mn',
  Myanmar_Burmese: 'my',
  Nepali: 'ne',
  Norwegian: 'no',
  Pashto: 'ps',
  Persian: 'fa',
  Polish: 'pl',
  Portuguese: 'pt',
  Punjabi: 'pa',
  Romanian: 'ro',
  Russian: 'ru',
  Samoan: 'sm',
  Scots_Gaelic: 'gd',
  Serbian: 'sr',
  Sesotho: 'st',
  Shona: 'sn',
  Sindhi: 'sd',
  Sinhala: 'si',
  Slovak: 'sk',
  Slovenian: 'sl',
  Somali: 'so',
  Spanish: 'es',
  Sundanese: 'su',
  Swahili: 'sw',
  Swedish: 'sv',
  Tajik: 'tg',
  Tamil: 'ta',
  Telugu: 'te',
  Thai: 'th',
  Turkish: 'tr',
  Ukrainian: 'uk',
  Urdu: 'ur',
  Uzbek: 'uz',
  Vietnamese: 'vi',
  Welsh: 'cy',
  Xhosa: 'xh',
  Yiddish: 'yi',
  Yoruba: 'yo',
  Zulu: 'zu',
};

export const LanguageMapping: Record<string, Array<string>> = {
  Automatic: ['google', 'google2', 'libre', 'argos', 'bing', 'gpt4o'],
  Afrikaans: ['google', 'google2', 'bing', 'gpt4o'],
  Albanian: ['google', 'google2', 'bing', 'gpt4o'],
  Amharic: ['google', 'google2', 'bing', 'gpt4o'],
  Arabic: ['google', 'google2', 'libre', 'argos', 'bing', 'gpt4o'],
  Assamese: ['bing'],
  Armenian: ['google', 'google2', 'bing', 'gpt4o'],
  Azerbaijani: ['google', 'google2', 'libre', 'bing', 'gpt4o'],
  Bashkir: ['bing'],
  Basque: ['google', 'google2', 'bing', 'gpt4o'],
  Belarusian: ['google', 'google2', 'gpt4o'],
  Bengali: ['google', 'google2', 'bing', 'gpt4o'],
  Bosnian: ['google', 'google2', 'bing', 'gpt4o'],
  Bulgarian: ['google', 'google2', 'bing', 'deepl', 'gpt4o'],
  Cantonese_Traditional: ['bing'],
  Catalan: ['google', 'google2', 'bing', 'gpt4o'],
  Cebuano: ['google', 'google2', 'gpt4o'],
  Chichewa: ['google', 'google2', 'gpt4o'],
  Chinese_Literary: ['bing'],
  Chinese_Simplified: [
    'google',
    'google2',
    'bing',
    'libre',
    'argos',
    'deepl',
    'gpt4o',
  ],
  Chinese_Traditional: ['google', 'google2', 'bing', 'gpt4o'],
  Corsican: ['google', 'google2', 'gpt4o'],
  Croatian: ['google', 'google2', 'bing', 'gpt4o'],
  Czech: ['google', 'google2', 'bing', 'libre', 'deepl', 'gpt4o'],
  Danish: ['google', 'google2', 'bing', 'libre', 'deepl', 'gpt4o'],
  Dari: ['bing'],
  Divehi: ['bing'],
  Dutch: ['google', 'google2', 'bing', 'libre', 'deepl', 'gpt4o'],
  English: ['google', 'google2', 'bing', 'libre', 'argos', 'deepl', 'gpt4o'],
  Esperanto: ['google', 'google2', 'libre', 'gpt4o'],
  Estonian: ['google', 'google2', 'bing', 'deepl', 'gpt4o'],
  Faroese: ['bing'],
  Fijian: ['bing'],
  Filipino: ['google', 'google2', 'bing', 'gpt4o'],
  Finnish: ['google', 'google2', 'bing', 'libre', 'deepl', 'gpt4o'],
  French: ['google', 'google2', 'bing', 'libre', 'argos', 'deepl', 'gpt4o'],
  French_Canada: ['bing'],
  Frisian: ['google', 'google2', 'gpt4o'],
  Galician: ['google', 'google2', 'bing', 'gpt4o'],
  Georgian: ['google', 'google2', 'bing', 'gpt4o'],
  German: ['google', 'google2', 'bing', 'libre', 'argos', 'deepl', 'gpt4o'],
  Greek: ['google', 'google2', 'bing', 'libre', 'deepl', 'gpt4o'],
  Gujarati: ['google', 'google2', 'bing', 'gpt4o'],
  Haitian_Creole: ['google', 'google2', 'bing', 'gpt4o'],
  Hausa: ['google', 'google2', 'gpt4o'],
  Hawaiian: ['google', 'google2', 'gpt4o'],
  Hebrew: ['google', 'google2', 'bing', 'libre', 'gpt4o'],
  Hindi: ['google', 'google2', 'bing', 'libre', 'argos', 'gpt4o'],
  Hmong: ['google', 'google2', 'bing', 'gpt4o'],
  Hungarian: ['google', 'google2', 'bing', 'libre', 'deepl', 'gpt4o'],
  Icelandic: ['google', 'google2', 'bing', 'gpt4o'],
  Igbo: ['google', 'google2', 'gpt4o'],
  Indonesian: ['google', 'google2', 'bing', 'libre', 'argos', 'deepl', 'gpt4o'],
  Inuinnaqtun: ['bing'],
  Inuktitut: ['bing'],
  Inuktitut_Latin: ['bing'],
  Irish: ['google', 'google2', 'bing', 'libre', 'argos', 'gpt4o'],
  Italian: ['google', 'google2', 'bing', 'libre', 'argos', 'deepl', 'gpt4o'],
  Japanese: ['google', 'google2', 'bing', 'libre', 'argos', 'deepl', 'gpt4o'],
  Javanese: ['google', 'google2', 'gpt4o'],
  Kannada: ['google', 'google2', 'bing', 'gpt4o'],
  Kazakh: ['google', 'google2', 'bing', 'gpt4o'],
  Khmer: ['google', 'google2', 'bing', 'gpt4o'],
  Klingon_Latin: ['bing'],
  Korean: ['google', 'google2', 'bing', 'libre', 'argos', 'deepl', 'gpt4o'],
  Kurdish_Kurmanji: ['google', 'google2', 'bing', 'gpt4o'],
  Kurdish_Northern: ['bing'],
  Kyrgyz: ['google', 'google2', 'bing', 'gpt4o'],
  Lao: ['google', 'google2', 'bing', 'gpt4o'],
  Latin: ['google', 'google2', 'gpt4o'],
  Latvian: ['google', 'google2', 'bing', 'deepl', 'gpt4o'],
  Lithuanian: ['google', 'google2', 'bing', 'deepl', 'gpt4o'],
  Luxembourgish: ['google', 'google2', 'gpt4o'],
  Macedonian: ['google', 'google2', 'bing', 'gpt4o'],
  Malagasy: ['google', 'google2', 'bing', 'gpt4o'],
  Malay: ['google', 'google2', 'bing', 'gpt4o'],
  Malayalam: ['google', 'google2', 'bing', 'gpt4o'],
  Maltese: ['google', 'google2', 'bing', 'gpt4o'],
  Maori: ['google', 'google2', 'bing', 'gpt4o'],
  Marathi: ['google', 'google2', 'bing', 'gpt4o'],
  Mongolian: ['google', 'google2', 'bing', 'gpt4o'],
  Mongolian_Cyrillic: ['bing'],
  Myanmar_Burmese: ['google', 'google2', 'bing', 'gpt4o'],
  Nepali: ['google', 'google2', 'bing', 'gpt4o'],
  Norwegian: ['google', 'google2', 'bing', 'deepl', 'gpt4o'],
  Odia: ['bing'],
  Pashto: ['google', 'google2', 'bing', 'gpt4o'],
  Persian: ['google', 'google2', 'bing', 'libre', 'gpt4o'],
  Polish: ['google', 'google2', 'bing', 'libre', 'argos', 'deepl', 'gpt4o'],
  Portuguese: ['google', 'google2', 'bing', 'libre', 'argos', 'deepl', 'gpt4o'],
  Portuguese_Brazil: ['bing'],
  Punjabi: ['google', 'google2', 'bing', 'gpt4o'],
  Querétaro_Otomi: ['bing'],
  Romanian: ['google', 'google2', 'bing', 'deepl', 'gpt4o'],
  Russian: ['google', 'google2', 'bing', 'libre', 'argos', 'deepl', 'gpt4o'],
  Samoan: ['google', 'google2', 'bing', 'gpt4o'],
  Scots_Gaelic: ['google', 'google2', 'gpt4o'],
  Serbian: ['google', 'google2', 'bing', 'gpt4o'],
  Serbian_Cyrillic: ['bing'],
  Sesotho: ['google', 'google2', 'gpt4o'],
  Shona: ['google', 'google2', 'gpt4o'],
  Sindhi: ['google', 'google2', 'gpt4o'],
  Sinhala: ['google', 'google2', 'gpt4o'],
  Slovak: ['google', 'google2', 'bing', 'libre', 'deepl', 'gpt4o'],
  Slovenian: ['google', 'google2', 'bing', 'deepl', 'gpt4o'],
  Somali: ['google', 'google2', 'bing', 'gpt4o'],
  Spanish: ['google', 'google2', 'bing', 'libre', 'argos', 'deepl', 'gpt4o'],
  Sundanese: ['google', 'google2', 'gpt4o'],
  Swahili: ['google', 'google2', 'bing', 'gpt4o'],
  Swedish: ['google', 'google2', 'bing', 'libre', 'deepl', 'gpt4o'],
  Tahitian: ['bing'],
  Tajik: ['google', 'google2', 'gpt4o'],
  Tamil: ['google', 'google2', 'bing', 'gpt4o'],
  Tatar: ['bing'],
  Telugu: ['google', 'google2', 'bing', 'gpt4o'],
  Thai: ['google', 'google2', 'bing', 'gpt4o'],
  Tibetan: ['bing'],
  Tigrinya: ['bing'],
  Tongan: ['bing'],
  Turkish: ['google', 'google2', 'bing', 'libre', 'argos', 'deepl', 'gpt4o'],
  Turkmen: ['bing'],
  Ukrainian: ['google', 'google2', 'bing', 'libre', 'deepl', 'gpt4o'],
  Upper_Sorbian: ['bing'],
  Urdu: ['google', 'google2', 'bing', 'gpt4o'],
  Uyghur: ['bing'],
  Uzbek: ['google', 'google2', 'bing', 'gpt4o'],
  Vietnamese: ['google', 'google2', 'bing', 'argos', 'gpt4o'],
  Welsh: ['google', 'google2', 'bing', 'gpt4o'],
  Xhosa: ['google', 'google2', 'gpt4o'],
  Yiddish: ['google', 'google2', 'gpt4o'],
  Yoruba: ['google', 'google2', 'gpt4o'],
  Yucatec_Maya: ['bing'],
  Zulu: ['google', 'google2', 'bing', 'gpt4o'],
};
